name: Deploy to ByteInspire Cloud project


on:
  push:
    branches:
      - release

jobs:
  build_and_deploy_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: byteinspire deploy
        uses: byteinspire/cloud-project-deployer-action@v1.0.2
        with:
          service-id: '${{ secrets.SERVICE_ID }}'
          token: '${{ secrets.ACCESS_TOKEN }}'
          directory: ./packages/server/main-server

  build_and_deploy_application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile
        
      - name: Build Package
        run: pnpm run build:all
        
      - name: byteinspire deploy
        uses: byteinspire/hosting-deployer-action@v1
        with:
          service-id: '${{ secrets.SERVICE_ID }}'
          token: '${{ secrets.ACCESS_TOKEN }}'
          directory: ./packages/application/main-application/dist
