name: Deploy to ByteInspire Cloud project


on:
  push:
    branches:
      - release

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: byteinspire/cloud-project-deployer-action@v1.0.2
        with:
          service-id: '${{ secrets.SERVICE_ID }}'
          token: '${{ secrets.ACCESS_TOKEN }}'
          directory: ./packages/server/main-server/
